export const MeasurementActions = {
  'ENABLE': 'EXPLORER_MEASUREMENT_ENABLE',
  'DISABLE': 'EXPLORER_MEASUREMENT_DISABLE',
  'SET_RANGE': 'EXPLORER_MEASUREMENT_SET_RANGE',
  'SET_ZERO': 'EXPLORER_MEASUREMENT_SET_ZERO',
  'SET_DIRECT_MEASUREMENTS': 'EXPLORER_MEASUREMENT_SET_DIRECT_MEASUREMENTS',
  'SET_RELATIVE_MEASUREMENTS': 'EXPLORER_MEASUREMENT_SET_RELATIVE_MEASUREMENTS',
  'CLEAR_ZERO': 'EXPLORER_MEASUREMENT_CLEAR_ZERO',
  'UPDATE_ZERO_MEASUREMENTS': 'EXPLORER_MEASUREMENT_UPDATE_ZERO_MEASUREMENTS',
  'SET_RELATIVE': 'EXPLORER_MEASUREMENT_SET_RELATIVE'
}