export const AnnotationUIActions = {
'ENABLE': 'EXPLORER_ANNOTATION_ENABLE',
'DISABLE': 'EXPLORER_ANNOTATION_DISABLE',
'SET_RANGE': 'EXPLORER_ANNOTATION_SET_RANGE',
'CLEAR_RANGE': 'EXPLORER_ANNOTATION_CLEAR_RANGE',
'SHOW_ANNOTATION': 'EXPLORER_ANNOTATION_SHOW',
'HIDE_ANNOTATION': 'EXPLORER_ANNOTATION_HIDE'
}