

export const DbAdminActions = {
  'SELECT_DB_ROOT': 'DBADMIN_SELECT_DB_ROOT',
  'SELECT_DB_FOLDER': 'DBADMIN_SELECT_DB_FOLDER',
  'SET_DB_FOLDER_MESSAGES': 'DBADMIN_SET_DB_FOLDER_MESSAGES',
  'CLEAR_DB_FOLDER_MESSAGES': 'DBADMIN_CLEAR_DB_FOLDER_MESSAGES',
  'SELECT_DB_STREAM': 'DBADMIN_SELECT_DB_STREAM',
  'SET_DB_ID': 'DBADMIN_SET_DB_ID'
};
