export const AccountActions = {
  'SET_NILMS_LOADED': 'ACCOUNT_SET_NILMS_LOADED',
  'SET_DATA_VIEWS_LOADED': 'ACCOUNT_SET_DATA_VIEWS_LOADED',
  'SET_USER_GROUPS_LOADED': 'ACCOUNT_SET_USER_GROUPS_LOADED',
  'SET_LOGGING_IN': 'ACCOUNT_SET_LOGGING_IN',
  'SET_NOT_LOGGING_IN': 'ACCOUNT_SET_NOT_LOGGING_IN'
}