export const InstallationActions = {
  'SELECT_DB_ROOT': 'INSTALLATION_SELECT_DB_ROOT',
  'SELECT_DB_FOLDER': 'INSTALLATION_SELECT_DB_FOLDER',
  'SET_DB_FOLDER_MESSAGES': 'INSTALLATION_SET_DB_FOLDER_MESSAGES',
  'CLEAR_DB_FOLDER_MESSAGES': 'INSTALLATION_CLEAR_DB_FOLDER_MESSAGES',
  'SELECT_DB_STREAM': 'INSTALLATION_SELECT_DB_STREAM',
  'SET_ROOT_FOLDER_ID': 'INSTALLATION_SET_ROOT_FOLDER_ID',
  'REFRESHING': 'INSTALLATION_REFRESHING',
  'REFRESHED': 'INSTALLATION_REFRESHED'
};
