export const InstallationActions = {
  'SELECT_DB_ROOT': 'INSTALLATION_SELECT_DB_ROOT',
  'SELECT_DB_FOLDER': 'INSTALLATION_SELECT_DB_FOLDER',
  'SELECT_DATA_APP': 'INSTALLATION_SELECT_DATA_APP',
  'SET_DB_FOLDER_MESSAGES': 'INSTALLATION_SET_DB_FOLDER_MESSAGES',
  'CLEAR_DB_FOLDER_MESSAGES': 'INSTALLATION_CLEAR_DB_FOLDER_MESSAGES',
  'SELECT_DB_STREAM': 'INSTALLATION_SELECT_DB_STREAM',
  'SET_NILM': 'INSTALLATION_SET_NILM',
  'REFRESHING': 'INSTALLATION_REFRESHING',
  'REFRESHED': 'INSTALLATION_REFRESHED'
};
