export const ExplorerActions = {
  'PLOT_ELEMENT': 'EXPLORER_PLOT_ELEMENT',
  'HIDE_ELEMENT': 'EXPLORER_HIDE_ELEMENT',
  'SHOW_PLOT': 'EXPLORER_SHOW_PLOT',
  'HIDE_PLOT': 'EXPLORER_HIDE_PLOT',
  'ADD_PLOT_DATA': 'EXPLORER_ADD_PLOT_DATA',
  'ADD_NAV_DATA': 'EXPLORER_ADD_NAV_DATA',
  'SET_PLOT_TIME_RANGE': 'EXPLORER_SET_PLOT_TIME_RANGE'
}